// <auto-generated />
namespace NastaniMK_2023.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class eventImage : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(eventImage));
        
        string IMigrationMetadata.Id
        {
            get { return "202307011103573_eventImage"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
