// <auto-generated />
namespace NastaniMK_2023.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class modificationvol2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(modificationvol2));
        
        string IMigrationMetadata.Id
        {
            get { return "202306302220225_modificationvol2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
